server:
  port: ${SERVER_PORT}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: airbnb-consumer
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}
    consumer:
      group-id: airbnb-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jira:
  url: ${JIRA_URL}
  username: ${JIRA_USERNAME}
  api-token: ${JIRA_API_TOKEN}
  project-key: ${JIRA_PROJECT_KEY}

logging:
  level:
    root: info